[#175897656] Add OTP delete after validation
pagopa/io-functions-cgn-merchant pull request #2
Opened 2021-03-10 17:46 UTC by AleDore

#### List of Changes
- Add delete after OTP validation
- Add tests

#### Motivation and Context
Since a merchant could set `invalidate_otp` to `true` if the OTP must be invalidated, we must provide delete operations in Redis key-value pair for:
- OTP
- FiscalCode-OTP
See this [story](https://www.pivotaltracker.com/story/show/175897656) for further informations.

#### How Has This Been Tested?
Unit tests done.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2021-03-15 09:33 UTC, AleDore commented
@balanza @BurnedMarshal: As balanza [suggests](https://github.com/pagopa/io-functions-commons/pull/135#issuecomment-799228950) I've added comments for both constants on [2955b4d](https://github.com/pagopa/io-functions-cgn-merchant/pull/2/commits/2955b4db513f47e9d4dbd14567d56d8f5177b0b2)

2021-03-15 09:35 UTC, BurnedMarshal commented
> @balanza @BurnedMarshal: As balanza [suggests](https://github.com/pagopa/io-functions-commons/pull/135#issuecomment-799228950) I've added comments for both constants on [2955b4d](https://github.com/pagopa/io-functions-cgn-merchant/pull/2/commits/2955b4db513f47e9d4dbd14567d56d8f5177b0b2)

Thanks @AleDore. We should add the comments even on `io-functions-cgn`

2021-03-16 09:16 UTC, AleDore commented
/azp run

2021-03-16 09:16 UTC, BurnedMarshal requested changes

2021-03-16 09:16 UTC, BurnedMarshal commented on ValidateOtp/__tests__/handler.test.ts
> +    expect(response.kind).toBe("IResponseErrorInternal");
```suggestion
    expect(deleteTaskMock).toBeCalledTimes(1);
    expect(response.kind).toBe("IResponseErrorInternal");
```

2021-03-16 09:16 UTC, BurnedMarshal commented on ValidateOtp/__tests__/handler.test.ts
> +    expect(response.kind).toBe("IResponseErrorInternal");
```suggestion
    expect(deleteTaskMock).toBeCalledTimes(1);
    expect(response.kind).toBe("IResponseErrorInternal");
```

2021-03-16 09:16 UTC, BurnedMarshal commented on ValidateOtp/__tests__/handler.test.ts
> +    expect(response.kind).toBe("IResponseErrorInternal");
```suggestion
    expect(deleteTaskMock).toBeCalledTimes(2);
    expect(response.kind).toBe("IResponseErrorInternal");
```

2021-03-16 09:16 UTC, BurnedMarshal commented on ValidateOtp/__tests__/handler.test.ts
> +    expect(response.kind).toBe("IResponseSuccessJson");
```suggestion
    expect(deleteTaskMock).toBeCalledTimes(2);
    expect(deleteTaskMock).toHaveBeenNthCalledWith(
      1,
      expect.any(Object),
      `${OTP_PREFIX}${aValidationPayloadWithInvalidation.otp_code}`
    );
    expect(deleteTaskMock).toHaveBeenNthCalledWith(
      2,
      expect.any(Object),
      `${OTP_FISCAL_CODE_PREFIX}${anOtpPayload.fiscalCode}`
    );
    expect(response.kind).toBe("IResponseSuccessJson");
```

2021-03-16 09:25 UTC, BurnedMarshal requested changes

2021-03-16 09:25 UTC, BurnedMarshal commented on ValidateOtp/handler.ts
>          ResponseErrorInternal("Cannot validate OTP Code")
On the errors scenarios, we haven't any log. Could be useful to log for debugging reason. Make sure doesn't log confidential data like text plain OTP.

2021-03-16 14:24 UTC, BurnedMarshal approved these changes
LGTM apart two minor changes

2021-03-16 14:24 UTC, BurnedMarshal commented on ValidateOtp/handler.ts
> +    return retrieveOtp(redisClient, otpCode)
The new constant seems useless, can we remove it?
```suggestion
    const errorLogMapping = mapWithPrivacyLog(
      context,
      logPrefix,
      payload.otp_code
    );
    return retrieveOtp(redisClient, payload.otp_code)
```

2021-03-16 14:24 UTC, BurnedMarshal commented on utils/logging.ts
> +  stringToObfuscate?: string
Can we use a `NonEmptyString` type?
```suggestion
  stringToObfuscate?: NonEmptyString
```

2021-03-16 14:55 UTC, merged